apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebackend
  labels:
    app: nodebackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodebackend
  template:
    metadata:
      labels:
        app: nodebackend
    spec:
      containers:
        - name: nodebackend
          image: 500230242536.dkr.ecr.ap-south-1.amazonaws.com/samplenode-app:7a0d38a2c54f86ba1391c78379e86ff07e6478b8
          ports:
            - containerPort: 8000
          imagePullPolicy: Always