apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebackend
  labels:
    app: nodebackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodebackend
  template:
    metadata:
      labels:
        app: nodebackend
    spec:
      containers:
        - name: nodebackend
          image: 500230242536.dkr.ecr.ap-south-1.amazonaws.com/samplenode-app:5402f18bc0736cbba83b85abd64d057b88fb704e
          ports:
            - containerPort: 8000
          imagePullPolicy: Always