# This workflow will build and push a new container image to Amazon ECR,

name: Push Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 500230242536.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: samplenode-app


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: samplenode-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR so that it can
        docker build -t samplenode-app .
        docker tag samplenode-app:latest 500230242536.dkr.ecr.ap-south-1.amazonaws.com/samplenode-app:latest
        docker push 500230242536.dkr.ecr.ap-south-1.amazonaws.com/samplenode-app:latest

  # # Updating the image in kube manifest file in another github repository    

  # update-deployment:
  #   name: Update Deployment Manifest
  #   runs-on: ubuntu-latest
  #   needs: deploy

  #   steps:

    - name: Checkout Deployment Repo
      uses: actions/checkout@v2
      with:
        repository: kari-venkatesh/GitOps-Project-Appilication-Code
        ref: main  # Optionally, specify a branch or tag here if needed
        token: ${{ secrets.KUBE_REPO_ACCESS_TOKEN }}
  
    - name: Update Deployment Manifest
      run: |
        # Replace the image reference in deployment.yaml
        sed -i "s|image: .*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest|g" kube/deployment.yaml

    - name: Commit and push updated deployment manifest
      run: |        
          git config --global user.email "karivenkatesh23@gmail.com"
          git config --global user.name "kari-venkatesh"
          git add kube/deployment.yaml
          git commit -m "Update deployment manifest with new image"
          git push origin HEAD:${{ github.ref }}
