# This workflow will build and push a new container image to Amazon ECR,

name: Push Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sample-node-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR so that it can
        docker build -t sample-node-app .
        docker tag sample-node-app:latest 500230242536.dkr.ecr.ap-south-1.amazonaws.com/sample-node-app:latest
        docker push 500230242536.dkr.ecr.ap-south-1.amazonaws.com/sample-node-app:latest
        
  update-deployment:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout Deployment Repo
      uses: actions/checkout@v2
      with:
        repository: life-in-devops/GitOps-Project-EKS
        ref: main  # Optionally, specify a branch or tag here if needed
        token: ${{ secrets.KUBE_REPO_ACCESS_TOKEN }}
        # path: kube
   
    - name: List Files in kube Directory
      run: |
        ls -la  # List contents of the root directory
        if [ ! $? -eq 0 ]; then
          echo "Error: Failed to list files in kube directory"
          exit 1
        fi 

    - name: Update Deployment Manifest
      run: |
        # Replace the image reference in deployment.yaml
        sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}|g" kube/deployment.yaml

    - name: Commit and push updated deployment manifest
      run: |
          git config --global user.email "lifeindevops@gmail.com"
          git config --global user.name "life-in-devops"

          git add kube/deployment.yaml
          git commit -m "Update deployment manifest with new image"
          git push origin HEAD:${{ github.ref }}
